---
cidr_networks:
  container: 172.29.236.0/22
  tunnel: 172.29.240.0/22
  storage: 172.29.244.0/22

used_ips:
  - "172.29.236.1,172.29.236.50"
  - "172.29.240.1,172.29.240.50"
  - "172.29.244.1,172.29.244.50"
  - "172.29.248.1,172.29.248.50"

global_overrides:
  internal_lb_vip_address: 172.29.236.8
  external_lb_vip_address: 172.29.236.9
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
    - network:
        container_bridge: "br-overlay"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel"
        type: "geneve"
        range: "1:1000"
        net_name: "geneve"
        group_binds:
          - neutron_ovn_controller
        is_container_address: true
    - network:
        container_bridge: "br-provider"
        container_type: "veth"
        container_interface: "eth11"
        network_interface: "bond1"
        type: "vlan"
        range: "101:200,301:400"
        net_name: "vlan"
        group_binds:
          - neutron_ovn_controller
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute

###
### Infrastructure
###

# galera, memcache, rabbitmq, utility
shared-infra_hosts:
  infra01:
    ip: 172.29.236.11
  infra02:
    ip: 172.29.236.12
  infra03:
    ip: 172.29.236.13

# repository (apt cache, python packages, etc)
repo-infra_hosts:
  infra01:
    ip: 172.29.236.11
  infra02:
    ip: 172.29.236.12
  infra03:
    ip: 172.29.236.13

# load balancer
haproxy_hosts:
  infra01:
    ip: 172.29.236.11
  infra02:
    ip: 172.29.236.12
  infra03:
    ip: 172.29.236.13

# os-infra_hosts
os-infra_hosts:
  infra01:
    ip: 172.29.236.11
  infra02:
    ip: 172.29.236.12
  infra03:
    ip: 172.29.236.13

###
### OpenStack
###

# keystone
identity_hosts:
  infra01:
    ip: 172.29.236.11
  infra02:
    ip: 172.29.236.12
  infra03:
    ip: 172.29.236.13

# cinder api services
storage-infra_hosts:
  infra01:
    ip: 172.29.236.11
  infra02:
    ip: 172.29.236.12
  infra03:
    ip: 172.29.236.13

# nova api, conductor, etc services
compute-infra_hosts:
  infra01:
    ip: 172.29.236.11
  infra02:
    ip: 172.29.236.12
  infra03:
    ip: 172.29.236.13

# heat
orchestration_hosts:
  infra01:
    ip: 172.29.236.11
  infra02:
    ip: 172.29.236.12
  infra03:
    ip: 172.29.236.13

# horizon
dashboard_hosts:
  infra01:
    ip: 172.29.236.11
  infra02:
    ip: 172.29.236.12
  infra03:
    ip: 172.29.236.13

# neutron server, agents (L3, etc)
network_hosts:
  infra01:
    ip: 172.29.236.11
  infra02:
    ip: 172.29.236.12
  infra03:
    ip: 172.29.236.13

network-northd_hosts:
  infra01:
    ip: 172.29.236.11
  infra02:
    ip: 172.29.236.12
  infra03:
    ip: 172.29.236.13

network-gateway_hosts:
  compute01:
    ip: 172.29.236.21
  compute02:
    ip: 172.29.236.22

# ceilometer (telemetry data collection)
metering-infra_hosts:
  infra01:
    ip: 172.29.236.11
  infra02:
    ip: 172.29.236.12
  infra03:
    ip: 172.29.236.13

# aodh (telemetry alarm service)
metering-alarm_hosts:
  infra01:
    ip: 172.29.236.11
  infra02:
    ip: 172.29.236.12
  infra03:
    ip: 172.29.236.13

# gnocchi (telemetry metrics storage)
metrics_hosts:
  infra01:
    ip: 172.29.236.11
  infra02:
    ip: 172.29.236.12
  infra03:
    ip: 172.29.236.13

# nova hypervisors
compute_hosts:
  compute01:
    ip: 172.29.236.21
  compute02:
    ip: 172.29.236.22

# ceilometer compute agent (telemetry data collection)
metering-compute_hosts:
  compute01:
    ip: 172.29.236.21
  compute02:
    ip: 172.29.236.22

# cinder volume hosts (rbd-backed)
storage_hosts:
  storage01:
    ip: 172.29.236.41
  storage02:
    ip: 172.29.236.42
  storage03:
    ip: 172.29.236.43
